packages:
  - "apps/*"
  - "libs/**"
  - "tools/*"
allowBuilds:
  "@biomejs/biome": true
  "@datadog/pprof": false
  "@nestjs/core": true
  "@newrelic/fn-inspect": false
  "@newrelic/native-metrics": false
  "@parcel/watcher": true
  "@scarf/scarf": false
  "@swc/core": true
  lefthook: true
  less: true
  nx: true
  protobufjs: false
  sharp: true
  unrs-resolver: true

autoInstallPeers: true

catalog:
  "@biomejs/biome": 2.4.16
  "@nestjs/common": 11.1.28
  "@nestjs/core": 11.1.28
  "@nestjs/platform-express": 11.1.28
  "@nestjs/schematics": 11.1.0
  "@nestjs/testing": 11.1.28
  "@nx-go/nx-go": 4.0.0
  "@nx/angular": 23.1.0
  "@nx/docker": 23.1.0
  "@nx/express": 23.1.0
  "@nx/jest": 23.1.0
  "@nx/js": 23.1.0
  "@nx/nest": 23.1.0
  "@nx/next": 23.1.0
  "@nx/node": 23.1.0
  "@nx/react": 23.1.0
  "@nx/web": 23.1.0
  "@nx/webpack": 23.1.0
  "@nx/workspace": 23.1.0
  "@swc-node/register": 1.11.1
  "@swc/core": 1.15.40
  "@swc/helpers": 0.5.23
  "@swc/jest": 0.2.39
  "@types/jest": 30.0.0
  "@types/node": 25.9.1
  axios: 1.16.1
  jest: 30.4.2
  jest-environment-node: 30.4.1
  lefthook: 2.1.9
  nx: 23.1.0
  reflect-metadata: 0.2.2
  rxjs: 7.8.2
  ts-jest: 29.4.11
  ts-node: 10.9.2
  tslib: 2.8.1
  typescript: 6.0.3
  webpack-cli: 7.2.1
