package httpedge

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"net/http"

	"go.opentelemetry.io/otel/trace"

	"github.com/mateusmacedo/dmpf/libs/backend/go/ports"
	"github.com/mateusmacedo/dmpf/libs/backend/go/transport/deadline"

	"github.com/mateusmacedo/dmpf/apps/backend/bookings/application"
)

// Mux binds every declared route to its handler under the edge's own time
// policy, so a route the contract names and nobody serves fails to compile.
func Mux(service application.Service, budget deadline.Budget) *http.ServeMux {
	h := Handlers{Service: service}
	handlers := [5]http.HandlerFunc{
		h.ReserveBooking, h.CancelBooking, h.RegisterResource, h.FindBooking, h.FindBookingByResource,
	}

	mux := http.NewServeMux()
	for i, route := range Routes(budget) {
		mux.Handle(route.Method+" "+route.Path, withRouteDeadline(route.Budget, handlers[i]))
	}
	return mux
}

// edgeLocale answers the other mandatory field of CTX-01 that this edge has no
// source for: it publishes no content negotiation.
const edgeLocale = "en"

const identifierBytes = 16

// WHY: this edge authenticates nobody yet, so subject and tenant stay absent —
// absence is the truthful shape of an edge with no identity provider wired, and
// inventing either would be the filler value IDN-20 forbids.
func executionOf(r *http.Request) (ports.ExecutionContext, error) {
	deadline, governed := r.Context().Deadline()
	if !governed {
		return ports.ExecutionContext{}, errors.New("httpedge: the route mounted no deadline")
	}
	identifier := newIdentifier()
	return ports.NewExecutionContext(ports.ExecutionContextSpec{
		RequestID:     identifier,
		CorrelationID: identifier,
		TraceContext:  trace.SpanFromContext(r.Context()).SpanContext().TraceID().String(),
		Deadline:      ports.Instant(deadline.UnixNano()),
		Locale:        edgeLocale,
	})
}

func newIdentifier() string {
	buffer := make([]byte, identifierBytes)
	if _, err := rand.Read(buffer); err != nil {
		panic("httpedge: the operating system's entropy source failed: " + err.Error())
	}
	return hex.EncodeToString(buffer)
}

// WHY: the deadline of CTX-01 is regenerated by the edge policy (FND-07 §3.5),
// never taken from the caller — a value from the entry that widened it is
// refused, and a limit the edge does not apply governs nothing.
func withRouteDeadline(budget deadline.Budget, next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx, cancel := context.WithTimeout(r.Context(), budget.Limit)
		defer cancel()
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
