package httpedge

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"net/http"

	"go.opentelemetry.io/otel/trace"

	"github.com/mateusmacedo/dmpf/libs/backend/go/authn"
	provider "github.com/mateusmacedo/dmpf/libs/backend/go/http"
	"github.com/mateusmacedo/dmpf/libs/backend/go/ports"
	"github.com/mateusmacedo/dmpf/libs/backend/go/transport/deadline"

	"github.com/mateusmacedo/dmpf/apps/backend/bookings/application"
)

// Mux binds every declared route to its handler under the edge's own time
// policy, so a route the contract names and nobody serves fails to compile, and
// one that demands a subject without declaring a permission refuses to start.
func Mux(service application.Service, budget deadline.Budget, authenticator ports.Authenticator) (*http.ServeMux, error) {
	h := Handlers{Service: service}
	handlers := [5]http.HandlerFunc{
		h.ReserveBooking, h.CancelBooking, h.RegisterResource, h.FindBooking, h.FindBookingByResource,
	}

	mux := http.NewServeMux()
	for i, route := range Routes(budget) {
		if err := route.ValidateEdge(); err != nil {
			return nil, err
		}
		mounted := withExecutionContext(authenticator, route, handlers[i])
		mux.Handle(route.Method+" "+route.Path, withRouteDeadline(route.Budget, mounted))
	}
	return mux, nil
}

// edgeLocale answers the other mandatory field of CTX-01 that this edge has no
// source for: it publishes no content negotiation.
const edgeLocale = "en"

const identifierBytes = 16

// withExecutionContext authenticates, mounts the nine-field context and
// deposits it on the carrier, which is the single path from here to the
// provider (CTX-03, ADR-049). It runs inside withRouteDeadline, never outside:
// the deadline is mandatory in CTX-01 and has to exist before the context does.
func withExecutionContext(authenticator ports.Authenticator, route provider.Route, next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		limit, governed := r.Context().Deadline()
		if !governed {
			writeRejection(w, http.StatusInternalServerError, "internal-failure", "the request could not be completed")
			return
		}

		identity, status, code := provider.ResolveIdentity(r.Context(), authenticator, route, authn.CredentialFrom(r))
		if status == 0 {
			status, code = provider.RefuseAssertedIdentity(r, identity)
		}
		if status != 0 {
			writeRejection(w, status, code, "the request was not authenticated")
			return
		}

		identifier := newIdentifier()
		execution, err := ports.NewExecutionContext(ports.ExecutionContextSpec{
			RequestID:     identifier,
			CorrelationID: identifier,
			TraceContext:  trace.SpanFromContext(r.Context()).SpanContext().TraceID().String(),
			Subject:       identity.Subject,
			Tenant:        identity.Tenant,
			Permissions:   identity.Permissions,
			Deadline:      ports.Instant(limit.UnixNano()),
			Locale:        edgeLocale,
		})
		if err != nil {
			writeRejection(w, http.StatusInternalServerError, "internal-failure", "the request could not be completed")
			return
		}

		next.ServeHTTP(w, r.WithContext(ports.WithExecutionContext(r.Context(), execution)))
	})
}

func newIdentifier() string {
	buffer := make([]byte, identifierBytes)
	if _, err := rand.Read(buffer); err != nil {
		panic("httpedge: the operating system's entropy source failed: " + err.Error())
	}
	return hex.EncodeToString(buffer)
}

// WHY: the deadline of CTX-01 is regenerated by the edge policy (FND-07 §3.5),
// never taken from the caller — a value from the entry that widened it is
// refused, and a limit the edge does not apply governs nothing.
func withRouteDeadline(budget deadline.Budget, next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx, cancel := context.WithTimeout(r.Context(), budget.Limit)
		defer cancel()
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
