package httpedge

import (
	"context"
	"net/http"

	"github.com/mateusmacedo/dmpf/libs/backend/go/transport/deadline"

	"github.com/mateusmacedo/dmpf/apps/backend/bookings/application"
)

// Mux binds every declared route to its handler under the edge's own time
// policy, so a route the contract names and nobody serves fails to compile.
func Mux(service application.Service, budget deadline.Budget) *http.ServeMux {
	h := Handlers{Service: service}
	handlers := [5]http.HandlerFunc{
		h.ReserveBooking, h.CancelBooking, h.RegisterResource, h.FindBooking, h.FindBookingByResource,
	}

	mux := http.NewServeMux()
	for i, route := range Routes(budget) {
		mux.Handle(route.Method+" "+route.Path, withRouteDeadline(route.Budget, handlers[i]))
	}
	return mux
}

// WHY: the deadline of CTX-01 is regenerated by the edge policy (FND-07 §3.5),
// never taken from the caller — a value from the entry that widened it is
// refused, and a limit the edge does not apply governs nothing.
func withRouteDeadline(budget deadline.Budget, next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx, cancel := context.WithTimeout(r.Context(), budget.Limit)
		defer cancel()
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
