// Code generated by fixture. DO NOT EDIT.

package gerado

import "net/http"

// Gerar não isenta: este arquivo é consumido em runtime e responde pelas regras
// do bloco que o declara, exatamente como código escrito à mão.
func G() string { return http.MethodPost }
