apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/mateusmacedo/orders
    newTag: hmg

replicas:
  - name: orders-api
    count: 2

patches:
  - path: configmap-orders-patch.yaml
  - path: deployment-orders-api-patch.yaml
