apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/mateusmacedo/reservations
    newTag: hmg

replicas:
  - name: reservations-api
    count: 2

patches:
  - path: configmap-reservations-patch.yaml
  - path: deployment-reservations-api-patch.yaml
  - path: deployment-reservations-relay-patch.yaml
  - path: deployment-reservations-consumer-patch.yaml
