apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3200
      targetPort: http
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
