apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/mateusmacedo/reservations
    newTag: dev

secretGenerator:
  - name: reservations
    literals:
      - PG_DSN=postgres://reservations:reservations-dev@postgres-0.postgres:5432/reservations?sslmode=disable
      - KAFKA_BROKERS=redpanda-0.redpanda:9092
    options:
      disableNameSuffixHash: true

patches:
  - path: configmap-reservations-patch.yaml
  - path: deployment-reservations-api-patch.yaml
