apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/mateusmacedo/bff
    newTag: hmg

replicas:
  - name: bff
    count: 2

patches:
  - path: configmap-bff-patch.yaml
  - path: deployment-bff-patch.yaml
