apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  template:
    spec:
      containers:
        - name: bff
          volumeMounts:
            - name: grpc-ca
              mountPath: /etc/dmpf/grpc
              readOnly: true
            - name: grpc-client
              mountPath: /etc/dmpf/grpc-client
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              memory: 512Mi
      volumes:
        - name: grpc-ca
          secret:
            secretName: bff-grpc-ca
        - name: grpc-client
          secret:
            secretName: bff-grpc-client
